name: pengo
description: User-experience first booking application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_config: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^6.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  lottie: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  skeleton_animation: ^0.1.4
  socket_io_client: ^1.0.1
  syncfusion_flutter_datepicker: ^19.2.49

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/svg/shapes/
    - assets/svg/logo/
    - assets/svg/icons/
    - assets/lottie/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
