const String PREFIX_PATH = 'assets/svg/icons';

const String GOOCARD_ICON_PATH = PREFIX_PATH + '/goo.svg';
const String COUPON_ICON_PATH = PREFIX_PATH + '/coupon.svg';
const String SCAN_ICON_PATH = PREFIX_PATH + '/scan.svg';
const String INFO_ICON_PATH = PREFIX_PATH + '/info.svg';
const String REVIEW_ICON_PATH = PREFIX_PATH + '/review.svg';
const String SHARE_ICON_PATH = PREFIX_PATH + '/share.svg';
const String REPORT_ICON_PATH = PREFIX_PATH + '/report.svg';
const String HISTORY_ICON_PATH = PREFIX_PATH + '/history.svg';
const String TICKET_ICON_PATH = PREFIX_PATH + '/ticket.svg';
const String LOCATION_ICON_PATH = PREFIX_PATH + '/location.svg';
const String PROFILE_ICON_PATH = PREFIX_PATH + '/profile.svg';
const String SETTING_ICON_PATH = PREFIX_PATH + '/setting.svg';
const String LOGOUT_ICON_PATH = PREFIX_PATH + '/logout.svg';
const String COMMENT_TREE_PATH = PREFIX_PATH + '/comment-tree.svg';
const String HOLDING_PATH = PREFIX_PATH + '/hold.svg';
const String SHIELD_ICON_PATH = PREFIX_PATH + '/shield.svg';
const String EYE_ICON_PATH = PREFIX_PATH + '/eye.svg';
